#!/usr/bin/env zsh
if [[ "$(uname)" =~ "Darwin" ]]; then
    if [ -z "$(command -v brew)" ]; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    if [ -z "$(command -v ccls)" ]; then
        command sudo chown -R "${whoami}":admin /usr/local/bin /usr/local/etc /usr/local/sbin
        command chmod u+w /usr/local/bin /usr/local/etc /usr/local/sbin
        brew install tmuxinator ccls mosh coreutils binutils diffutils ed findutils \
            gawk watch wdiff gpatch rsync less openssh ctags go node llvm neofetch \
            zsh git tmux vim
    fi
else
    if [ -z "$(command -v ccls)" ]; then
        sudo snap install ccls --classic
        sudo apt-get install tmuxinator zsh git mosh neofetch ctags go nodejs npm \
            vim-gtk3 tmux llvm less openssh-server coreutils binutils diffutils ed \
            findutils gawk watch wdiff gpatch rsync
    fi
fi

cd "${HOME}"

#
# Install dircolors-solarized
#
if [[ ! -d "${HOME}/.dircolors/" ]]; then
    echo
    echo "Installing dircolors-solarized"
    curl -fLo ${HOME}/.dircolors/dircolors.ansi-dark --create-dirs \
        https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark
    if [[ -f $HOME/.dircolors/dircolors.ansi-dark ]]; then
        eval `dircolors $HOME/.dircolors/dircolors.ansi-dark`
    fi
fi

#
# Install powerline-fonts
#
if [[ ! -d "${HOME}/.local/share/fonts/" ]]; then
    curl -fLo ${HOME}/.local/share/fonts/DejaVu_Sans_Mono_for_Powerline.ttf --create-dirs \
        https://github.com/powerline/fonts/raw/master/DejaVuSansMono/DejaVu%20Sans%20Mono%20for%20Powerline.ttf
    curl -fLo ${HOME}/.local/share/fonts/DejaVu_Sans_Mono_Oblique_for_Powerline.ttf --create-dirs \
        https://github.com/powerline/fonts/raw/master/DejaVuSansMono/DejaVu%20Sans%20Mono%20Oblique%20for%20Powerline.ttf
    curl -fLo ${HOME}/.local/share/fonts/DejaVu_Sans_Mono_Bold_for_Powerline.ttf --create-dirs \
        https://github.com/powerline/fonts/raw/master/DejaVuSansMono/DejaVu%20Sans%20Mono%20Bold%20for%20Powerline.ttf
    curl -fLo ${HOME}/.local/share/fonts/DejaVu_Sans_Mono_Bold_Oblique_for_Powerline.ttf --create-dirs \
        https://github.com/powerline/fonts/raw/master/DejaVuSansMono/DejaVu%20Sans%20Mono%20Bold%20Oblique%20for%20Powerline.ttf
    fc-cache -f -v
fi

#
# Install autojump
#
if [ -z "$(command -v autojump)" ]; then
    echo
    echo "Installing autojump"
    command git clone git://github.com/wting/autojump.git
    cd autojump
    ./install.py
fi

#
# Install pip3
#
if [ -z "$(command -v pip3)" ]; then
    echo
    echo "Installing pip3"
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python3 get-pip.py
fi

#
# Install ranger
#
if [ -z "$(command -v ranger)" ]; then
    echo
    echo "Installing ranger"
    command sudo python3 -m pip install ranger-fm
fi

#
# Install flake8
#
if [ -z "$(command -v flake8)" ]; then
    echo
    echo "Installing flake8"
    command sudo python3 -m pip install flake8
fi

#
# Install jedi
#
if [ -z "$(pip list | command grep -i jedi)" ]; then
    echo
    echo "Installing jedi"
    command sudo python3 -m pip install jedi
fi

#
# Install eslint
#
if [ -z "$(command -v eslint)" ]; then
    echo
    echo "Installing eslint"
    npm install -g eslint
    # ./node_modules/.bin/eslint --init
fi

#
# Install tsserver
#
if [ -z "$(command -v tsserver)" ]; then
    echo
    echo "Installing tsserver"
    npm install -g typescript
fi

#
# Install oh-my-zsh
#
if [[ ! -d "${HOME}/.oh-my-zsh" ]]; then
    echo
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

#
# Clean up
#
echo
echo "Cleaning up autojump"
if [[ -d "${HOME}/autojump" ]]; then
    command rm -rf "${HOME}/autojump"
fi

echo
echo "Cleaning up get-pip.py"
if [[ -f "${HOME}/get-pip.py" ]]; then
    command rm -rf "${HOME}/get-pip.py"
fi

echo
echo "==> Successfully executed all tasks"
