#!/usr/bin/env bash

export LANG=en_US.UTF-8

# Desktop/Screen-related services
xset -dpms &
xset s off &
dunst &

# Remap CapsLock key
setxkbmap -option caps:escape &

# Set screen brightness at last
xbacklight -set 0
xbacklight -set 70

feh --bg-center "${HOME}/.config/i3/arch-white.png" --bg-center "${HOME}/.config/i3/arch-white.png"

# Startup applications
/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg) &
gsettings set org.gnome.settings-daemon.plugins.cursor active false &

ibus-daemon --xim --replace --daemonize &

/usr/bin/megasync &

killall dropbox &
if [[ -f "${HOME}"/.dropbox-dist/dropboxd ]]; then
    "${HOME}"/.dropbox-dist/dropboxd &
elif [[ -f /opt/dropbox/dropboxd ]]; then
    /opt/dropbox/dropboxd &
fi

# /etc/lightdm/lightdm-display.sh
